version: '3.9'

services:
  couchdb:
    restart: always
    image: couchdb:3.3.2
    environment:
      COUCHDB_USER: couchdb_user
      COUCHDB_PASSWORD: couchdb_password
    ports:
      - "5984:5984"
    volumes:
      - ./couchdb:/opt/couchdb/data

  localstack:
    image: localstack/localstack-full:0.12.11
    environment:
      SERVICES: s3
      DEFAULT_REGION: us-east-1
    ports:
      - "4566:4566"
    volumes:
      - ./localstack:/tmp/localstack
    command: "start"
